name: Deploy to Firebase Hosting on PR
'on': pull_request
jobs:
  build_and_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          curl -s https://raw.githubusercontent.com/leoafarias/fvm/master/install.sh | bash &&
          export PATH="$PATH:$HOME/.pub-cache/bin" &&
          fvm install 3.10.5 &&
          fvm use 3.10.5 &&
          fvm flutter channel stable &&
          fvm flutter pub get &&
          fvm flutter config --enable-web &&
          fvm flutter build web
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_RESUL_CAY }}'
          projectId: resul-cay
