name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          wget https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.10.5-stable.tar.xz &&
          tar xf flutter_linux_3.10.5-stable.tar.xz &&
          export PATH="$PATH:$PWD/flutter/bin" &&
          flutter channel stable &&
          flutter pub get &&
          flutter config --enable-web &&
          flutter build web --release
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_RESUL_CAY }}'
          channelId: live
          projectId: resul-cay
